[options]
bootstrap_before = 'myspacevim#before'
bootstrap_after = 'myspacevim#after'

colorscheme = "gruvbox"
colorscheme_bg = "dark"

enable_guicolors = true

statusline_separator = "arrow"
statusline_iseparator = "arrow"

buffer_index_type = 1

enable_tabline_filetype_icon = true

enable_statusline_mode = true

# update every startup
automatic_update = true 

# disable default 's' windows leader
windows_leader = ','

# In vim the , key repeats the last last f, F, t and T, but in SpaceVim it is
# the language specific Leader key. To disable this feature, set the option
# enable_language_specific_leader to false.
enable_language_specific_leader = false

# disable jk as <Esc> 
escape_key_binding = '' 

# enable VCS integration for the file tree
enable_filetree_gitstatus = true 

# change the default searching tool to fd
file_searching_tools = ['fd', 'fd']

# This layer provides auto-completion in SpaceVim.
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "smart"

# This layer provides debug workflow for SpaceVim. All of the functionality is
# based on vim-vebugger.
[[layers]]
name = "debug"

# Enable fuzzy finder
[[layers]]
name = "denite"

# The format layer provides code formatting for SpaceVim, with support for
# neoformat (default) and codefmt underlying code formatting plugins.
[[layers]]
name = "format"
format_on_save = true

# Enable git integration
[[layers]]
name = 'git'

# This layer adds Assembly language support to SpaceVim.
[[layers]]
name = "lang#assembly"

# This layer is for golang development. It also provides additional
# language-specific key mappings.
[[layers]]
name = "lang#go"

# Enable C layer
[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true

# This layer is for Java development.
[[layers]]
name = "lang#java"
format_on_save = true

# This layer is for Python development.
[[layers]]
name = "lang#python"
enable_typeinfo = true
enabled_linters = ['python', 'pylint']
format_on_save = true

# This layer is for shell script development. Shell script includes bash, zsh
# and fish scripts.
[[layers]]
name = "lang#sh"

# This layer is for toml development.
[[layers]]
name = "lang#toml"

# This layer is for writing vim script, including code completion, syntax
# checking and buffer formatting
[[layers]]
name = "lang#vim"

# This layers adds extensive support for language-server-protocol.
[[layers]]
name = "lsp"
enabled_clients = ['pyright']

# Normal shell on the top
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# sudo layer provides the ability to read and write files with elevated
# privileges.
[[layers]]
name = "sudo"

# Enable version control integration
[[layers]]
name = 'VersionControl'

[[custom_plugins]]
repo = 'ryanoasis/vim-devicons'

# `merged` option is used for merging plugins directory.
# When `merged` is `true`, all files in this custom plugin
# will be merged into `~/.cache/vimfiles/.cache/init.vim/`
# for neovim or `~/.cache/vimfiles/.cache/vimrc/` for vim.
merged = false
