gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ initiate-free-draw-button '<Control><Alt>Button1'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ initiate-line-button '<Control><Alt><Shift>Button2'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ erase-button '<Control><Alt>Button3'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ clear-key '<Control><Alt>k'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ initiate-rectangle-button '<Control><Alt><Shift>Button1'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ initiate-ellipse-button '<Control><Alt><Shift>Button2'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ clear-button '<Shift><Control><Alt>Button3'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ erase-button '<Control><Alt>Button3'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ clear-key '<Shift><Control><Alt>k'
gsettings set org.compiz.annotate:/org/compiz/profiles/Default/plugins/annotate/ initiate-line-button '<Control><Alt>Button2'
gsettings set org.compiz.commands:/org/compiz/profiles/Default/plugins/commands/ command20 ''
gsettings set org.compiz.commands:/org/compiz/profiles/Default/plugins/commands/ run-command20-key ''
gsettings set org.compiz.commands:/org/compiz/profiles/Default/plugins/commands/ run-command20-key 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ raise-window-button 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ lower-window-button '<Super>Button4'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ maximize-window-key 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ minimize-window-key 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ lower-window-button '<Super>Button4'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ raise-window-button 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ unmaximize-or-minimize-window-key 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ window-menu-button 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ toggle-window-maximized-key '<Super>KP_0'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ toggle-window-shaded-key 'Disabled'
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ hsize 3
gsettings set org.compiz.core:/org/compiz/profiles/Default/plugins/core/ vsize 2
gsettings set org.compiz.ezoom:/org/compiz/profiles/Default/plugins/ezoom/ zoom-in-button '<Control><Alt>Button4'
gsettings set org.compiz.ezoom:/org/compiz/profiles/Default/plugins/ezoom/ zoom-out-button '<Control><Alt>Button5'
gsettings set org.compiz.gnomecompat:/org/compiz/profiles/Default/plugins/gnomecompat/ run-command-terminal-key '<Super>T'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-center-key '<Super>KP_5'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-left-key '<Super>KP_4'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-right-key '<Super>KP_6'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-top-key '<Super>KP_8'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-bottom-key '<Super>KP_2'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-topleft-key '<Super>KP_7'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-topright-key '<Super>KP_9'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-bottomleft-key '<Super>KP_1'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-bottomright-key '<Super>KP_3'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ put-restore-key 'Disabled'
gsettings set org.compiz.grid:/org/compiz/profiles/Default/plugins/grid/ cycle-sizes true
gsettings set org.compiz.move:/org/compiz/profiles/Default/plugins/move/ initiate-button '<Super>Button1'
gsettings set org.compiz.opengl:/org/compiz/profiles/Default/plugins/opengl/ lighting true
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ next-all-key '<Super>Tab'
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ prev-all-key '<Shift><Super>Tab'
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ focus-on-switch true
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ bring-to-front true
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ brightness 80
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ saturation 80
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ opacity 95
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ mipmap true
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ highlight-mode 1
gsettings set org.compiz.staticswitcher:/org/compiz/profiles/Default/plugins/staticswitcher/ popup-delay 0.05
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ left-key '<Super>j'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ right-key '<Super>l'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ up-key '<Super>k'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ down-key '<Super>j'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ left-window-key '<Super><Shift>h'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ right-window-key '<Super><Shift>l'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ up-window-key '<Super><Shift>k'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ down-window-key '<Super><Shift>j'
gsettings set org.compiz.wall:/org/compiz/profiles/Default/plugins/wall/ left-key '<Super>h'

