repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        exclude: '.*\.(zshrc|zprofile|p10k\.zsh)$'  # Exclude ZSH config files that use ZSH-specific syntax

  - repo: local
    hooks:
      - id: shfmt
        name: Format shell scripts with shfmt
        entry: shfmt
        language: system
        args: ['-w', '-s', '-i', '2']  # Write changes, simplify code, 2-space indentation
        files: \.(sh|bash)$
        types: [shell]
