repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        # args: [-e, SC1091]
        # SC1091: Not following sourced files (dotfiles often source non-tracked files)
        exclude: '.*\.(zshrc|zprofile|p10k\.zsh)$'  # Exclude ZSH config files that use ZSH-specific syntax
